"""
generate_data.py -- regenerate every table and figure used in the paper
    ../paper/collatz_multiverse.tex

Run:  python3 generate_data.py [--quick]

Outputs land in ./data/ as both human-readable .txt and \\input-able .tex.
Two kinds of output:

  * TABLES -- data/<name>.tex, a run of tabular rows, spliced by
    inline_tables.py between the "% >>>BEGIN-DATA <name>" markers.
  * INLINE FIGURES -- data/facts.tex, a run of \\newcommand definitions for
    every number the paper quotes in a *sentence*.  These used to be typed
    into the .tex and they drifted (the q-ary residue-obstruction counts
    ended up contradicting the verification table that produced them), so
    the prose now uses \\Fact... macros and nothing measured is typed by hand.

The verification suite runs last and its results are a table too, so a check
that starts failing is visible in the paper rather than only on the console.
"""

from __future__ import annotations

import argparse
import math
import os
import sys
import time
from typing import Dict, List, Sequence, Tuple

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import multiverse as mv
import qary as QA
from multiverse import (Family, Fate, classify, decompose_cycles, find_cycles,
                        growth_statistics, normal_form, reduction_chain,
                        cycle_equation_residual)

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "data")
os.makedirs(DATA, exist_ok=True)


def write(name: str, text: str) -> None:
    r"""Write a data file.

    LaTeX subtlety: a file ending in a tabular row separator `\\` cannot be
    \input inside a tabular.  TeX peeks past the `\\` for an optional `[len]`
    argument, that lookahead crosses the end of the input file, and the
    `\bottomrule` waiting in the outer document is then read while the
    alignment is still mid-row -- "Misplaced \noalign".  So we strip a
    trailing `\\` here, and the paper supplies it before `\bottomrule`.
    """
    if name.endswith(".tex"):
        stripped = text.rstrip()
        if stripped.endswith(r"\\"):
            text = stripped[:-2].rstrip() + "\n"
    path = os.path.join(DATA, name)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"  wrote {os.path.relpath(path, HERE)}  ({len(text)} bytes)")


# ======================================================================
#  Inline figures
#
#  Every table in the paper is spliced in from data/ by inline_tables.py.
#  The figures quoted in *sentences* used to be typed straight into the .tex,
#  and they drifted: the residue-obstruction counts in the q-ary chapter were
#  left over from an older parameter setting and contradicted the very row of
#  the verification table that produced them.  So those numbers are now
#  emitted here as LaTeX macros (data/facts.tex), and the paper uses the
#  macros.  Nothing quoted in the paper is typed by hand any more.
# ======================================================================

FACTS: Dict[str, str] = {}


def _num(n: int) -> str:
    r"""12345 -> "12{,}345", the thousands separator the paper uses."""
    return "{,}".join(reversed([str(n)[max(0, i - 3):i]
                                for i in range(len(str(n)), 0, -3)]))


def write_facts() -> None:
    # A TeX control word is letters only, so a key with a digit in it produces
    # a macro LaTeX cannot parse -- and the failure is a wall of "Missing
    # number" errors a long way from the cause.  Catch it here instead.
    bad = sorted(k for k in FACTS if not k.isalpha())
    if bad:
        raise SystemExit("fact names must be letters only, got: "
                         + ", ".join(bad))
    body = "\n".join(r"\newcommand{\Fact%s}{%s}" % (k, v)
                     for k, v in sorted(FACTS.items()))
    write("facts.tex", "%% generated by generate_data.py -- do not edit\n"
          + body + "\n")
    write("facts.txt",
          "Inline figures quoted in the paper's prose\n" + "=" * 74 + "\n\n"
          + "\n".join(f"  {k:<24} {v}" for k, v in sorted(FACTS.items()))
          + "\n")


# ======================================================================
#  The primality map (the "beyond modularity" chapter)
# ======================================================================

def primality_census(limit: int):
    """Cycles and basin sizes of the primality map over seeds 1..limit.

    Memoised across seeds, so the whole range costs one pass.  Returns
    (cycles, basins, failed, peak) with `cycles` a list of sorted tuples
    ordered by decreasing basin and `peak` the largest value reached from any
    seed in the range -- which is how far the density experiment below can and
    cannot see.
    """
    pm = QA.primality_map()
    settled: Dict[int, int] = {}
    index: Dict[Tuple[int, ...], int] = {}
    basin: Dict[int, int] = {}
    failed = 0
    peak = [0]                      # largest value any orbit from 1..limit hits
    for seed in range(1, limit + 1):
        n, seen, traj = seed, {}, []
        while True:
            if n in settled:
                cid = settled[n]
                break
            if n in seen:
                key = tuple(sorted(traj[seen[n]:]))
                cid = index.setdefault(key, len(index))
                break
            if len(traj) > 100000:
                cid = -1
                failed += 1
                break
            seen[n] = len(traj)
            traj.append(n)
            n = pm.step(n)
        basin[cid] = basin.get(cid, 0) + 1
        for x in traj:
            settled[x] = cid
        if traj:
            peak[0] = max(peak[0], max(traj))
    order = sorted(index.items(), key=lambda kv: -basin.get(kv[1], 0))
    return ([k for k, _ in order],
            [basin.get(i, 0) for _, i in order],
            failed, peak[0])


def facts_qdrift() -> None:
    """The two q = 3 examples the drift section quotes."""
    FACTS["QDriftLow"] = "%.3f" % QA.qary_drift(QA.QMap(3, (3, 3), (1, 1)))
    FACTS["QDriftHigh"] = "%.3f" % QA.qary_drift(QA.QMap(3, (5, 7), (1, 1)))


def table_primcycles(limit: int) -> None:
    cycles, basins, failed, peak = primality_census(limit)
    lines = [f"Primality map  f(n) = 3n+1 (n prime), n/2 (n even), n+1 (else)",
             f"seeds 1..{limit}:  {failed} failed to become periodic",
             "=" * 74, ""]
    tex = []
    for k, (c, bn) in enumerate(zip(cycles, basins), start=1):
        lines.append(f"  C{k}: period {len(c)}, basin {100*bn/limit:.1f}%")
        lines.append(f"      {list(c)}")
        tex.append(r"  C_{%d} &= \{%s\}, &&\text{period } %d, &&%.1f\%%"
                   r" \text{ of seeds}%s" %
                   (k, ",".join(str(x) for x in c), len(c),
                    100.0 * bn / limit, r"," if k < len(cycles) else "."))
    write("primcycles.txt", "\n".join(lines) + "\n")
    write("primcycles.tex", "%% generated by generate_data.py -- do not edit\n"
          + " \\\\\n".join(tex) + "\n")
    FACTS["PrimSeeds"] = _num(limit)
    FACTS["PrimPeak"] = r"%.1f \times 10^{%d}" % (
        peak / 10 ** int(math.log10(peak)), int(math.log10(peak)))
    FACTS["PrimCycleCount"] = {1: "one", 2: "two", 3: "three"}.get(
        len(cycles), str(len(cycles)))


#: (floor, first seed, how many seeds).  Each row of the density table is its
#: OWN sample, drawn just above the floor it reports -- orbits started at
#: n <= 200000 never reach 10^8 at all, so a single seed range cannot fill the
#: table.  An earlier version printed the rows without saying this, and the
#: counts were visibly non-monotone as a result.
PRIME_BANDS = [(10 ** 3, 1, 4000),
               (10 ** 4, 10 ** 5, 2500),
               (10 ** 6, 10 ** 7, 1800),
               (10 ** 8, 10 ** 9, 1200),
               (10 ** 11, 10 ** 12, 900)]


def table_primedensity(quick: bool) -> None:
    """Density of primes among the odd values on the TRANSIENT part of an
    orbit of the primality map, above a floor.

    Cycles are excluded: they are short and prime-rich, and counting them
    makes the density look alarmingly close to the ln2/ln3 threshold.
    """
    pm = QA.primality_map()
    rows = []
    for floor, lo, count in PRIME_BANDS:
        if quick:
            count = min(count, 120)
        tot = pr = 0
        for seed in range(lo, lo + count):
            traj, ci = pm.orbit(seed, max_steps=6000, value_cap=10 ** 40)
            seg = traj[:ci] if ci is not None else traj
            for y in seg:
                if y % 2 == 1 and y > floor:
                    tot += 1
                    pr += QA.is_prime(y)
        rows.append((floor, lo, count, tot, pr,
                     100.0 * pr / max(tot, 1), 100.0 / math.log(floor)))

    lines = ["Primes among odd transient values of the primality map",
             "(each row is its own sample of seeds, drawn just above its "
             "floor)", "=" * 74, "",
             f"{'above':>10} {'seeds':>24} {'odd':>8} {'prime':>8} "
             f"{'density':>9} {'1/ln n':>9}"]
    for floor, lo, count, tot, pr, dens, ref in rows:
        lines.append(f"{floor:>10.0e} {f'{lo}..{lo+count-1}':>24} {tot:>8} "
                     f"{pr:>8} {dens:>8.1f}% {ref:>8.1f}%")
    write("primedensity.txt", "\n".join(lines) + "\n")

    def p10(x):
        return "10^{%d}" % round(math.log10(x))

    tex = [r"$%s$ & $%s$ & $%s$ & $%s$ & $%s$ & $%.1f\%%$ & $%.1f\%%$ \\" %
           (p10(floor), _num(lo), _num(count), _num(tot), _num(pr), dens, ref)
           for floor, lo, count, tot, pr, dens, ref in rows]
    write("primedensity.tex",
          "%% generated by generate_data.py -- do not edit\n"
          + "\n".join(tex) + "\n")
    # the same count taken over WHOLE orbits, cycles included -- the
    # measurement the paper warns against, quoted so the warning is concrete
    whole = []
    for lo, hi in ((1, 400), (10 ** 5, 10 ** 5 + 200)):
        tot = pr = 0
        for seed in range(lo, hi):
            traj, _ = pm.orbit(seed, max_steps=6000, value_cap=10 ** 40)
            for y in traj:
                if y % 2 == 1:
                    tot += 1
                    pr += QA.is_prime(y)
        whole.append(100.0 * pr / max(tot, 1))
    FACTS["PrimeDensWholeLo"] = "%d" % round(min(whole))
    FACTS["PrimeDensWholeHi"] = "%d" % round(max(whole))

    top = rows[-1]
    FACTS["PrimeDensTopFloor"] = "10^{%d}" % round(math.log10(top[0]))
    FACTS["PrimeDensTop"] = "%.1f" % top[5]
    FACTS["PrimeDensTopRef"] = "%.1f" % top[6]
    FACTS["PrimeDensRatio"] = "%.1f" % (top[5] / top[6])


# ======================================================================
#  Table 1 -- the classification grid
# ======================================================================

def table_grid(a_max: int = 12, b_max: int = 12) -> None:
    write("grid.txt", mv.render_grid(a_max, b_max) + "\n")

    # LaTeX version, coloured by family
    colour = {
        Family.CONSTANT: "gCon", Family.PURE_SHAPE: "gShp",
        Family.PURE_RUNAWAY: "gRun", Family.PARITY_RUNAWAY: "gRun",
        Family.HALVING: "gHal", Family.ATTRACTING: "gAtt",
        Family.DESCENT: "gDes", Family.PRIMITIVE: "gOpen",
    }
    rows = []
    header = " & ".join([r"$a\backslash b$"] + [str(b) for b in range(b_max + 1)])
    rows.append(header + r" \\ \midrule")
    for a in range(a_max + 1):
        cells = []
        for b in range(b_max + 1):
            u = classify(a, b)
            cells.append(r"\cell{%s}{%s}" % (colour[u.family], mv.CODE[u.family]))
        rows.append(f"${a}$ & " + " & ".join(cells) + r" \\")
    body = "\n".join(rows)
    spec = "r" + "c" * (b_max + 1)
    write("grid.tex",
          "%% generated by generate_data.py -- do not edit\n"
          "\\begin{tabular}{@{}%s@{}}\n\\toprule\n%s\n\\bottomrule\n\\end{tabular}\n"
          % (spec, body))


# ======================================================================
#  Table 2 -- carykh's 6x6 grid, fully resolved
# ======================================================================

def table_carykh() -> None:
    lines = ["carykh's 6x6 grid (a = 0..5 down, b = 0..5 across), fully resolved",
             "=" * 78, ""]
    tex = []
    tally: Dict[str, int] = {}
    for a in range(6):
        for b in range(6):
            u = classify(a, b)
            tally[u.family] = tally.get(u.family, 0) + 1
            nf = f"{u.normal[0]}x{u.normal[1]:+d}"
            same = (u.a, u.b) == u.normal
            fate = "OPEN" if u.fate == Fate.OPEN else u.fate.upper()
            lines.append(f"  {u.label:<7} {u.family:<20} {fate:<32} "
                         f"{'' if same else '-> ' + nf}")
            if a >= 1 and b >= 1 and a % 2 == 1 and b % 2 == 1:
                tex.append((u.label, u.family, u.fate, nf, same))
    lines.append("")
    lines.append("family tally over the 36 cells:")
    for k, v in sorted(tally.items(), key=lambda kv: -kv[1]):
        lines.append(f"  {k:<22} {v}")

    # the nine cells carykh left unresolved
    lines.append("")
    lines.append("carykh's nine 'unique' universes (a, b both odd, both >= 1):")
    nine = [(a, b) for a in (1, 3, 5) for b in (1, 3, 5)]
    for a, b in nine:
        u = classify(a, b)
        nf = f"{u.normal[0]}x{u.normal[1]:+d}"
        verdict = {
            Fate.CYCLIC: "SOLVED: every orbit cycles",
            Fate.OPEN: "open",
        }.get(u.fate, u.fate)
        extra = "" if (u.a, u.b) == u.normal else f"  (equivalent to {nf})"
        lines.append(f"  {u.label:<6} {verdict}{extra}")
    distinct = sorted({classify(a, b).normal for a, b in nine
                       if classify(a, b).fate == Fate.OPEN})
    lines.append("")
    lines.append(f"  => genuinely open and pairwise inequivalent: "
                 + ", ".join(f"{a}x{b:+d}" for a, b in distinct))
    write("carykh_grid.txt", "\n".join(lines) + "\n")

    rows = []
    for a, b in nine:
        u = classify(a, b)
        nf = f"${u.normal[0]}x{u.normal[1]:+d}$"
        if u.fate == Fate.CYCLIC:
            st = r"\solved{every orbit cycles}"
        elif (u.a, u.b) != u.normal:
            st = r"\reduc{equivalent to %s}" % nf
        else:
            st = r"\openv{open}"
        rows.append(r"$%dx%+d$ & %s & %s \\" % (u.a, u.b, u.family.replace("_", " "), st))
    write("carykh_nine.tex",
          "%% generated by generate_data.py -- do not edit\n" + "\n".join(rows) + "\n")


# ======================================================================
#  Table 3 -- cycle census for the 3x+b row  (Artem's chart)
# ======================================================================

def table_row_cycles(a: int, b_max: int, seed_max: int, max_steps: int,
                     stem: str) -> List[Tuple[int, int, int, Tuple[int, int]]]:
    """Cycle counts for T_{a,b}, b odd, 1 <= b <= b_max."""
    out = []
    t0 = time.time()
    for b in range(1, b_max + 1, 2):
        cs = find_cycles(a, b, seed_max=seed_max, max_steps=max_steps)
        prim = [c for c in cs if c.is_primitive]
        out.append((b, len(cs), len(prim), normal_form(a, b)))
    print(f"    ({time.time() - t0:.1f}s)")

    lines = [f"Cycle census for f(x) = {a}x + b,  b odd <= {b_max}",
             f"search: seeds 1..{seed_max}, step budget {max_steps}",
             "counts are LOWER BOUNDS -- a cycle whose basin misses the seed "
             "window is not found",
             "=" * 78, "",
             f"{'b':>5} {'cycles':>7} {'primitive':>10} {'normal form':>14}  notes"]
    for b, n, p, nf in out:
        u = classify(a, b)
        note = []
        if u.attracting:
            note.append("attracting " + ",".join(f"{q}^{e}" for q, e in sorted(u.attracting.items())))
        if u.repelling:
            note.append("repelling " + ",".join(f"{q}^{e}" for q, e in sorted(u.repelling.items())))
        lines.append(f"{b:>5} {n:>7} {p:>10} {nf[0]}x{nf[1]:+d}".ljust(40)
                     + "; ".join(note))
    write(f"{stem}.txt", "\n".join(lines) + "\n")

    # LaTeX: 4 columns of (b, total, primitive)
    per = (len(out) + 3) // 4
    cols = [out[i * per:(i + 1) * per] for i in range(4)]
    body = []
    for r in range(per):
        cells = []
        for c in cols:
            if r < len(c):
                b, n, p, _ = c[r]
                cells += [str(b), str(n), str(p)]
            else:
                cells += ["", "", ""]
        body.append(" & ".join(cells) + r" \\")
    write(f"{stem}.tex",
          "%% generated by generate_data.py -- do not edit\n" + "\n".join(body) + "\n")
    return out


# ======================================================================
#  Table 4 -- the divisor decomposition, worked
# ======================================================================

def table_decomposition(a: int, bs: Sequence[int], seed_max: int,
                        max_steps: int) -> None:
    lines = ["Divisor decomposition of the cycle set",
             "",
             "  Cyc(T_{a,b})  =  disjoint union over odd d | b  of  "
             "d * PrimCyc(T_{a, b/d})",
             "",
             "verified by grouping each cycle by its repelling-prime content "
             "and dividing through",
             "=" * 78]
    tex = []
    for b in bs:
        cs = find_cycles(a, b, seed_max=seed_max, max_steps=max_steps)
        groups = decompose_cycles(a, b, cs)
        lines.append("")
        lines.append(f"f(x) = {a}x + {b}   ({len(cs)} cycles found)")
        pieces = []
        for d, cl in groups.items():
            sub = f"{a}x{b // d:+d}"
            lines.append(f"   d = {d:<5}  {len(cl):>2} cycle(s)  =  {d} * "
                         f"primitive cycles of {sub}")
            for c in cl:
                lines.append(f"        len {c.length:<3} k={c.k:<3} m={c.m:<3} "
                             f"min={c.minimum:<7} max={c.maximum:<12} "
                             f"eqn residual {cycle_equation_residual(c)}")
            pieces.append(r"%d{\cdot}\mathrm{P}(%dx%+d)^{%d}" % (d, a, b // d, len(cl)))
        tex.append(r"$%dx%+d$ & $%d$ & $%s$ \\" % (a, b, len(cs), " \\;\\sqcup\\; ".join(pieces)))
    write("decomposition.txt", "\n".join(lines) + "\n")
    write("decomposition.tex",
          "%% generated by generate_data.py -- do not edit\n" + "\n".join(tex) + "\n")


# ======================================================================
#  Table 5 -- density of open universes
# ======================================================================

def table_density(limits: Sequence[int]) -> None:
    """Two densities.

      * ALL open universes -- those whose normal form is primitive with
        a' >= 3.  Since the normal form has a' = a / 2^s with
        s = min(v2(a), v2(b)), a universe is open iff v2(a) = v2(b) and
        a / 2^s >= 3.  Powers of two have density 0, so the predicted
        density is  P(v2(a) = v2(b)) = sum_s 4^{-s-1} = 1/3.

      * IRREDUCIBLE open universes -- those already in normal form:
        a >= 3 odd, b odd, gcd(a, b) = 1.  Predicted density
        (1/4) * prod_{p odd}(1 - p^-2) = (1/4)(8/pi^2) = 2/pi^2.
    """
    third = 1 / 3
    twopi = 2 / math.pi ** 2
    lines = ["Density of open universes",
             "",
             "  open              : normal form is primitive (a' >= 3 odd, b' odd)",
             "  open irreducible  : additionally already in normal form,",
             "                      i.e. a >= 3 odd, b odd, gcd(a,b) = 1",
             "",
             f"  predicted open density         = 1/3     = {third:.6f}",
             f"  predicted irreducible density  = 2/pi^2  = {twopi:.6f}",
             "=" * 78, "",
             f"{'N':>7} {'open':>10} {'open irr':>10} {'proved':>10} "
             f"{'open/N^2':>10} {'1/3':>8} {'irr/N^2':>10} {'2/pi^2':>10}"]
    rows = []
    for N in limits:
        op = opi = pr = 0
        for a in range(1, N + 1):
            for b in range(1, N + 1):
                u = classify(a, b)
                if u.fate == Fate.OPEN:
                    op += 1
                    if not u.is_reducible:
                        opi += 1
                else:
                    pr += 1
        f1, f2 = op / (N * N), opi / (N * N)
        lines.append(f"{N:>7} {op:>10} {opi:>10} {pr:>10} {f1:>10.6f} "
                     f"{third:>8.4f} {f2:>10.6f} {twopi:>10.6f}")
        rows.append(r"$%d$ & $%d$ & $%.6f$ & $%d$ & $%.6f$ \\"
                    % (N, op, f1, opi, f2))
    write("density.txt", "\n".join(lines) + "\n")
    write("density.tex",
          "%% generated by generate_data.py -- do not edit\n" + "\n".join(rows) + "\n")


# ======================================================================
#  Table 5b -- the knowledge ladder
# ======================================================================

def table_tiers(limits: Sequence[int]) -> None:
    """Census of the four Knowledge tiers, against their limiting densities.

        CLOSED     -> 2/3          (everything proved except the a=1 row)
        DECIDED    -> 0            (a' = 1 forces a to be a power of two)
        REDUCIBLE  -> 1/3 - 2/pi^2
        OPEN       -> 2/pi^2
    """
    pred = {
        mv.Knowledge.CLOSED:    2 / 3,
        mv.Knowledge.DECIDED:   0.0,
        mv.Knowledge.REDUCIBLE: 1 / 3 - 2 / math.pi ** 2,
        mv.Knowledge.OPEN:      2 / math.pi ** 2,
    }
    SHORT = {mv.Knowledge.CLOSED: "CLOSED", mv.Knowledge.DECIDED: "DECIDED",
             mv.Knowledge.REDUCIBLE: "REDUCIBLE", mv.Knowledge.OPEN: "OPEN"}
    lines = ["The knowledge ladder", "",
             "  CLOSED     fate proved AND the cycle set in closed form",
             "  DECIDED    fate proved, cycles computable, no formula in b",
             "  REDUCIBLE  fate unknown, but equivalent to a smaller open universe",
             "  OPEN       fate unknown and irreducible -- its own normal form",
             "",
             "limiting densities: " + ", ".join(
                 f"{SHORT[k]} {v:.6f}" for k, v in pred.items()),
             "=" * 78, "",
             f"{'N':>7} " + " ".join(f"{SHORT[k]:>12}" for k in mv.Knowledge.ORDER)]
    rows = []
    for N in limits:
        c = {k: 0 for k in mv.Knowledge.ORDER}
        for a in range(1, N + 1):
            for b in range(1, N + 1):
                c[mv.knowledge(a, b)] += 1
        tot = N * N
        lines.append(f"{N:>7} " + " ".join(f"{c[k] / tot:>12.6f}"
                                           for k in mv.Knowledge.ORDER))
        rows.append(r"$%d$ & %s \\" % (
            N, " & ".join(f"${c[k] / tot:.6f}$" for k in mv.Knowledge.ORDER)))
    lines.append("")
    lines.append(f"{'limit':>7} " + " ".join(
        f"{pred[k]:>12.6f}" for k in mv.Knowledge.ORDER))
    rows.append(r"limit & %s \\" % " & ".join(
        f"${pred[k]:.6f}$" for k in mv.Knowledge.ORDER))
    write("tiers.txt", "\n".join(lines) + "\n")
    write("tiers.tex",
          "%% generated by generate_data.py -- do not edit\n" + "\n".join(rows) + "\n")


# ======================================================================
#  Table 6 -- growth statistics heat map (carykh's average max growth)
# ======================================================================

def table_growth(a_max: int, b_max: int, n_max: int) -> None:
    """The relative-peak heat map, WITH the fraction of seeds it rests on.

    `growth_statistics` drops any seed that leaves the step or value budget
    before it repeats, and averages what is left.  For a contracting row that
    is every seed; for an expanding one it can be a few per cent, and the
    printed mean is then a conditional average over an exceptional set of
    non-diverging seeds rather than a typical value.  Reporting the peak
    without that percentage -- which an earlier version did -- makes the
    a >= 5 rows look comparable with the a <= 3 rows when they are not, so the
    counted percentage travels with every cell.
    """
    lines = [f"Average relative peak (geometric mean of max(orbit(n))/n) and "
             f"average path length,",
             f"over seeds n = 1..{n_max}.",
             "'RUN' = every seed exceeded the value or step budget (runaway).",
             "'counted' = percentage of the seeds that stayed inside the",
             "budget; the means are over those seeds only.",
             "=" * 78, ""]
    grid_peak: Dict[Tuple[int, int], object] = {}
    for a in range(0, a_max + 1):
        for b in range(0, b_max + 1):
            st = growth_statistics(a, b, n_max=n_max, max_steps=2000,
                                   value_cap=10 ** 24)
            grid_peak[(a, b)] = st
    hdr = "  a\\b " + "".join(f"{b:>9}" for b in range(b_max + 1))
    lines.append("AVERAGE RELATIVE PEAK")
    lines.append(hdr)
    for a in range(a_max + 1):
        cells = []
        for b in range(b_max + 1):
            st = grid_peak[(a, b)]
            cells.append("      RUN" if st["peak"] is None else f"{st['peak']:>9.3f}")
        lines.append(f"{a:>5} " + "".join(cells))
    lines.append("")
    lines.append("AVERAGE PATH LENGTH")
    lines.append(hdr)
    for a in range(a_max + 1):
        cells = []
        for b in range(b_max + 1):
            st = grid_peak[(a, b)]
            cells.append("      RUN" if st["path"] is None else f"{st['path']:>9.2f}")
        lines.append(f"{a:>5} " + "".join(cells))
    lines.append("")
    lines.append("PERCENTAGE OF SEEDS COUNTED")
    lines.append(hdr)
    for a in range(a_max + 1):
        cells = []
        for b in range(b_max + 1):
            st = grid_peak[(a, b)]
            pc = 100.0 * (1.0 - st["runaway_fraction"])
            cells.append("      RUN" if st["peak"] is None else f"{pc:>8.1f}%")
        lines.append(f"{a:>5} " + "".join(cells))
    write("growth.txt", "\n".join(lines) + "\n")

    rows = []
    worst = 100.0
    for a in range(a_max + 1):
        cells = []
        for b in range(b_max + 1):
            st = grid_peak[(a, b)]
            if st["peak"] is None:
                cells.append(r"\rn")
                continue
            pc = 100.0 * (1.0 - st["runaway_fraction"])
            if pc >= 99.95:
                cells.append(f"{st['peak']:.2f}")
            else:
                worst = min(worst, pc)
                cells.append(r"%.2f\,\pct{%d}" % (st["peak"], round(pc)))
        rows.append(f"${a}$ & " + " & ".join(cells) + r" \\")
    write("growth.tex",
          "%% generated by generate_data.py -- do not edit\n" + "\n".join(rows) + "\n")
    FACTS["GrowthSeeds"] = _num(n_max)
    FACTS["GrowthWorstCounted"] = "%d" % round(worst)
    # the three cells the text quotes to three decimals (LaTeX macro names
    # cannot contain digits, hence the spelled-out suffixes)
    for b, word in ((0, "Zero"), (2, "Two"), (6, "Six")):
        if b <= b_max and grid_peak[(2, b)]["peak"] is not None:
            FACTS["GrowthRowTwo" + word] = "%.3f" % grid_peak[(2, b)]["peak"]


# ======================================================================
#  The remaining inline figures
# ======================================================================

def facts_cycle_through_one(a_max: int, b_max: int) -> None:
    """How often 1 is periodic, and how often that is the one-step case."""
    tot = pw = 0
    for a in range(1, a_max, 2):
        for b in range(1, b_max, 2):
            per, _ = mv.one_is_periodic(a, b)
            if not per:
                continue
            tot += 1
            if (a + b) & (a + b - 1) == 0:
                pw += 1
    FACTS["OneAMax"] = _num(a_max)
    FACTS["OneBMax"] = _num(b_max)
    FACTS["OneTotal"] = _num(tot)
    FACTS["OnePow"] = _num(pw)
    FACTS["OneOther"] = _num(tot - pw)


def facts_c4(a_lo: int, a_hi: int, b_hi: int, seed_hi: int) -> None:
    r"""Counterexamples to conjecture C4.

    C4: if 1 lies on a cycle C containing another odd number, then no odd
    number outside C enters C.  The scan is over odd a in [a_lo, a_hi] -- the
    row a = 1 is excluded because it is solved outright by the descent
    theorem, and reporting it alongside the open rows conflates the two.
    """
    viol = []
    for a in range(a_lo, a_hi + 1, 2):
        for b in range(1, b_hi + 1, 2):
            t, ci = mv.orbit(1, a, b, max_steps=5000, value_cap=10 ** 40)
            if ci is None:
                continue
            C = set(t[ci:])
            if 1 not in C or sum(1 for x in C if x % 2) < 2:
                continue
            for seed in range(1, seed_hi, 2):
                if seed in C:
                    continue
                u, cj = mv.orbit(seed, a, b, max_steps=20000,
                                 value_cap=10 ** 40)
                if cj is not None and any(x in C for x in u):
                    viol.append((a, b, seed))
                    break
    FACTS["CfourALo"] = _num(a_lo)
    FACTS["CfourAHi"] = _num(a_hi)
    FACTS["CfourBHi"] = _num(b_hi)
    FACTS["CfourSeedHi"] = _num(seed_hi)
    FACTS["CfourViol"] = {1: "one", 2: "two", 3: "three", 4: "four", 5: "five",
                          6: "six", 7: "seven", 8: "eight",
                          9: "nine"}.get(len(viol), _num(len(viol)))


def facts_window(a: int, b: int, narrow: int, wide: int, steps: int) -> None:
    """The census entry that moves when the seed window widens."""
    FACTS["WindowB"] = _num(b)
    FACTS["WindowNarrow"] = _num(narrow)
    FACTS["WindowWide"] = _num(wide)
    FACTS["WindowNarrowCyc"] = _num(
        len(find_cycles(a, b, seed_max=narrow, max_steps=steps)))
    FACTS["WindowWideCyc"] = _num(
        len(find_cycles(a, b, seed_max=wide, max_steps=steps)))


# ======================================================================
#  Verification suite -- every theorem of the paper, checked numerically
# ======================================================================

def verify(quick: bool) -> None:
    R: List[Tuple[str, str, int, str]] = []   # (id, claim, cases, verdict)

    def rec(tag, claim, n, ok, detail=""):
        R.append((tag, claim, n, ("PASS" if ok else "FAIL " + detail)))
        print(f"    {tag:<8} {'PASS' if ok else 'FAIL'}  ({n} cases) {claim}")

    A = 40 if not quick else 16
    B = 40 if not quick else 16
    NN = 300 if not quick else 80
    STEPS = 400

    # -- Thm: halving symmetry.  Pointwise:  U = T_{2a,2b} satisfies
    #    U(n)  = T_{a,b}(n)                      for n even, and
    #    U(n)  = 2*T_{a,b}(n) (which is even),
    #    U^2(n)= T_{a,b}(n)                      for n odd.
    #    Hence the U-orbit of n is the T-orbit of n with one extra even term
    #    inserted after each odd step.
    n = 0
    ok = True
    for a in range(0, A):
        for b in range(0, B):
            U = lambda x: mv.step(x, 2 * a, 2 * b)
            for s in range(1, 200):
                n += 1
                if s % 2 == 0:
                    if U(s) != mv.step(s, a, b):
                        ok = False
                else:
                    if U(s) != 2 * mv.step(s, a, b) or U(s) % 2 != 0:
                        ok = False
                    if U(U(s)) != mv.step(s, a, b):
                        ok = False
    # and the orbit-level consequence: the U-trajectory is exactly the
    # T-trajectory with 2*T(x) spliced in after each odd x
    for a in range(0, A // 2):
        for b in range(0, B // 2):
            if a == 0 and b == 0:
                continue
            for s in range(1, 60):
                t1, _ = mv.orbit(s, a, b, max_steps=40, value_cap=10 ** 18)
                expect = []
                for x in t1:
                    expect.append(x)
                    if x % 2 == 1:
                        expect.append(2 * mv.step(x, a, b))
                t2, _ = mv.orbit(s, 2 * a, 2 * b, max_steps=len(expect),
                                 value_cap=10 ** 18)
                n += 1
                if t2 != expect[:len(t2)]:
                    ok = False
    rec("T-halve", "halving symmetry: T_{2a,2b} refines T_{a,b}", n, ok)

    # -- Thm: odd scaling.  d odd  =>  T_{a,db}(d n) = d T_{a,b}(n).
    n = 0
    ok = True
    for a in range(0, A):
        for b in range(0, B):
            for d in (1, 3, 5, 7, 9, 15):
                for s in range(1, 30):
                    n += 1
                    if mv.step(d * s, a, d * b) != d * mv.step(s, a, b):
                        ok = False
    rec("T-scale", "odd scaling: T_{a,db}(dn) = d T_{a,b}(n) for odd d", n, ok)

    # -- Thm: p-adic stratification (i), attraction.
    n = 0
    ok = True
    for a in range(1, A):
        for b in range(1, B):
            att = mv.attracting_primes(a, b)
            for p, e in att.items():
                D = p ** e
                for s in range(1, 60):
                    t, _ = mv.orbit(s, a, b, max_steps=200, value_cap=10 ** 24)
                    # after the e-th odd step the orbit must be inside D*Z forever
                    odd_seen = 0
                    entered = None
                    for i, x in enumerate(t):
                        if x % 2 == 1:
                            odd_seen += 1
                            if odd_seen >= e and entered is None:
                                entered = i + 1
                    if entered is not None and entered < len(t):
                        n += 1
                        if any(x % D for x in t[entered:]):
                            ok = False
    rec("T-attr", "attraction: p | gcd(a,b) forces every orbit into p^{v_p(b)}Z",
        n, ok)

    # -- Thm: p-adic stratification (ii), repulsion.
    n = 0
    ok = True
    for a in range(1, A):
        for b in range(1, B):
            rep = mv.repelling_primes(a, b)
            for p, e in rep.items():
                for s in range(1, 60):
                    t, _ = mv.orbit(s, a, b, max_steps=120, value_cap=10 ** 24)
                    inv = [min(mv.vp(x, p) if x % p == 0 else 0, e) for x in t if x]
                    n += 1
                    if len(set(inv)) > 1:
                        ok = False
    rec("T-rep", "repulsion: min(v_p(n), v_p(b)) is an orbit invariant when "
        "p | b, p does not divide a", n, ok)

    # -- Thm: normal form is coprime and idempotent.
    n = 0
    ok = True
    for a in range(1, 200):
        for b in range(1, 200):
            nf = normal_form(a, b)
            n += 1
            if math.gcd(nf[0], nf[1]) != 1:
                ok = False
            if normal_form(*nf) != nf:
                ok = False
    # the boundary the theorem excludes: at a = 0 every prime divides a, the
    # reduction is not defined, and coprimality genuinely fails -- so check
    # instead that nothing ever asks for it, i.e. that a = 0 is classified
    # outright as the constant family.
    for b in range(1, 200):
        n += 1
        if classify(0, b).family != Family.CONSTANT:
            ok = False
    rec("T-norm", "normal form is coprime and idempotent for a >= 1; a = 0 is "
        "classified without reduction", n, ok)

    # -- Thm: parity runaway.
    n = 0
    ok = True
    for a in range(1, A):
        for b in range(1, B):
            if (a + b) % 2 == 0:
                continue
            for s in range(1, 40):
                t, cyc = mv.orbit(s, a, b, max_steps=STEPS, value_cap=10 ** 400)
                n += 1
                if cyc is not None:
                    ok = False
    rec("T-parity", "a + b odd (a,b >= 1): no orbit is ever periodic", n, ok)

    # -- Thm: a = 1, b odd -- descent bound.
    n = 0
    ok = True
    for b in range(1, 120, 2):
        for s in range(1, 400):
            t, cyc = mv.orbit(s, 1, b, max_steps=4000)
            n += 1
            if cyc is None or min(t[cyc:]) > b:
                ok = False
    rec("T-desc", "a = 1, b odd: every orbit cycles, with least cycle element "
        "<= b", n, ok)

    # -- Thm: a = 0 -- unique cycle of length v2(b)+1.
    n = 0
    ok = True
    for b in range(1, 200):
        cs = find_cycles(0, b, seed_max=200, max_steps=200)
        n += 1
        if len(cs) != 1 or cs[0].length != mv.v2(b) + 1:
            ok = False
    rec("T-const", "a = 0: exactly one cycle, of length v_2(b) + 1", n, ok)

    # -- Thm: b = 0 -- shapes.
    n = 0
    ok = True
    for a in range(1, 40):
        u = classify(a, 0)
        pow2 = (a & (a - 1)) == 0
        n += 1
        if pow2 != (u.fate == Fate.CYCLIC):
            ok = False
        if pow2:
            for s in (1, 3, 5, 7, 9):
                t, c = mv.orbit(s, a, 0, max_steps=200)
                if c is None or len(t) - c != mv.v2(a) + 1 if a > 1 else False:
                    ok = False
    rec("T-shape", "b = 0: every orbit cycles iff a is a power of two, with "
        "period log2(a) + 1", n, ok)

    # -- Thm: cycle equation.
    n = 0
    ok = True
    pairs = [(a, b) for a in (1, 3, 5, 7, 9) for b in range(1, 40, 2)]
    for a, b in pairs:
        for c in find_cycles(a, b, seed_max=NN, max_steps=8000):
            n += 1
            if cycle_equation_residual(c) != 0:
                ok = False
    rec("T-cyceq", "cycle equation n1(2^m - a^k) = b * sum a^{k-i} 2^{...}", n, ok)

    # -- Thm: divisor decomposition of the cycle set.
    n = 0
    ok = True
    checks = [(3, b) for b in (5, 7, 15, 25, 35, 45, 49, 55, 63, 75, 77)]
    checks += [(5, b) for b in (3, 7, 9, 15, 21)]
    checks += [(7, b) for b in (3, 5, 9, 15)]
    for a, b in checks:
        cs = find_cycles(a, b, seed_max=NN * 4, max_steps=40000)
        for d, cl in decompose_cycles(a, b, cs).items():
            if d == 1:
                continue
            sub = find_cycles(a, b // d, seed_max=NN * 4, max_steps=40000)
            want = sorted(c.elements for c in sub if c.is_primitive)
            got = sorted(tuple(x // d for x in c.elements) for c in cl)
            n += 1
            if not set(map(tuple, want)) >= set(map(tuple, got)):
                ok = False
                print(f"      mismatch at {a}x+{b}, d={d}")
    rec("T-decomp", "divisor decomposition: the d-graded part of Cyc(T_{a,b}) "
        "is d * PrimCyc(T_{a,b/d})", n, ok)

    # -- Thm: attracting reduction preserves the cycle set exactly.
    n = 0
    ok = True
    for a in (3, 5, 7, 9):
        for b in range(1, 60, 2):
            u = classify(a, b)
            if not u.attracting:
                continue
            D = 1
            for p, e in u.attracting.items():
                D *= p ** e
            c1 = find_cycles(a, b, seed_max=800, max_steps=20000)
            c2 = find_cycles(a, b // D, seed_max=800, max_steps=20000)
            n += 1
            if sorted(tuple(x // D for x in c.elements) for c in c1) != \
               sorted(c.elements for c in c2):
                ok = False
                print(f"      mismatch at {a}x+{b} (D={D})")
    rec("T-attred", "attracting reduction is a bijection on cycles, scaling by D",
        n, ok)

    # -- Knowledge ladder: internal consistency of the four tiers.
    n = 0
    ok = True
    for a in range(0, 120):
        for b in range(0, 120):
            u = classify(a, b)
            k = mv.knowledge(a, b)
            nf = u.normal
            nu = classify(*nf)
            minimal = (u.a, abs(u.b)) == nf
            n += 1
            if k == mv.Knowledge.OPEN:
                ok &= (nu.fate == Fate.OPEN and minimal
                       and u.family == Family.PRIMITIVE)
            elif k == mv.Knowledge.REDUCIBLE:
                ok &= (nu.fate == Fate.OPEN and not minimal)
            elif k == mv.Knowledge.DECIDED:
                ok &= (nu.fate in Fate.PROVED and nu.family == Family.DESCENT)
            elif k == mv.Knowledge.CLOSED:
                ok &= (nu.fate in Fate.PROVED and nu.family != Family.DESCENT)
            else:
                ok = False
    rec("T-tier", "knowledge ladder: OPEN = minimal + open normal form, "
        "DECIDED = the a=1 row, CLOSED = proved with closed-form cycles", n, ok)

    # -- Z: invariance of the two half-lines, and finiteness of crossing.
    n = 0
    ok = True
    for a in range(0, 30):
        for b in range(-30, 31):
            escP = any(mv.step(x, a, b) <= 0 for x in range(1, 300))
            escN = any(mv.step(x, a, b) >= 0 for x in range(-300, 0))
            n += 2
            ok &= (escP != (a + b >= 1))
            ok &= (escN != (b <= a - 1))
    rec("T-Zhalf", "Z>0 invariant iff a+b >= 1; Z<0 invariant iff b <= a-1",
        n, ok)

    n = 0
    ok = True
    for a in range(1, 30):
        for b in range(-30, 31):
            for x in range(-400, 401):
                if x == 0:
                    continue
                y = mv.step(x, a, b)
                crossed = (x > 0 and y <= 0) or (x < 0 and y >= 0)
                n += 1
                if crossed and (x % 2 == 0 or abs(x) * a > abs(b)):
                    ok = False
    rec("T-Zcross", "sign changes only at odd n with |n| <= |b|/a", n, ok)

    # -- Thm: 1 is periodic iff its orbit meets a power of two.
    n = 0
    ok = True
    for a in range(1, 60):
        for b in range(1, 60):
            t, ci = mv.orbit(1, a, b, max_steps=4000, value_cap=10 ** 60)
            on = ci is not None and 1 in t[ci:]
            hits = any(x > 0 and (x & (x - 1)) == 0 for x in t[1:])
            n += 1
            ok &= (on == hits)
    rec("T-one", "1 lies on a cycle iff the orbit of 1 meets a power of two",
        n, ok)

    n = 0
    ok = True
    for b in range(1, 80):
        for k in range(1, 14):
            a = 2 ** k - b
            if a < 1:
                continue
            t, ci = mv.orbit(1, a, b, max_steps=200)
            n += 1
            ok &= (ci is not None and 1 in t[ci:] and len(t) - ci == k + 1)
    rec("T-onestep", "a + b = 2^k gives a cycle through 1 of period k+1", n, ok)

    # -- Thm: every cycle of x+b lies in [1, 2b].
    n = 0
    ok = True
    sharp = 0
    DESC_B = 159 if not quick else 39
    for b in range(1, DESC_B + 1, 2):
        for c in find_cycles(1, b, seed_max=4 * b + 40, max_steps=20000):
            n += 1
            ok &= (c.minimum >= 1 and c.maximum <= 2 * b and c.minimum <= b)
            sharp += (c.maximum == 2 * b)
    rec("T-desc2b", "every cycle of x+b is contained in [1, 2b]", n, ok)
    FACTS["DescB"] = _num(DESC_B)
    FACTS["DescCycles"] = _num(n)
    FACTS["DescSharp"] = _num(sharp)

    # -- Thm: the cycle-seed scaling needs m ODD.
    n = 0
    ok = True
    scale_hits = 0
    for a in (3, 5, 7):
        for b in (1, 3, 5):
            for c in find_cycles(a, b, seed_max=800, max_steps=20000):
                for m in (3, 5, 7, 9):
                    n += 1
                    img = tuple(m * x for x in c.elements)
                    hit = all(mv.step(img[i], a, m * b) == img[(i + 1) % len(img)]
                              for i in range(len(img)))
                    scale_hits += hit
                    ok &= hit
    rec("T-seedscale", "n on a cycle of ax+b => mn on a cycle of ax+mb for ODD m",
        n, ok)
    FACTS["ScaleCases"] = _num(n)
    FACTS["ScaleHits"] = _num(scale_hits)

    # the same census with EVEN m, which is where the earlier note went wrong
    ne = fe = 0
    for a in (3, 5, 7):
        for b in (1, 3, 5, 7):
            for c in find_cycles(a, b, seed_max=800, max_steps=20000):
                for m in (2, 4, 6, 8):
                    ne += 1
                    img = tuple(m * x for x in c.elements)
                    if not all(mv.step(img[i], a, m * b) == img[(i + 1) % len(img)]
                               for i in range(len(img))):
                        fe += 1
    FACTS["EvenMCases"] = _num(ne)
    FACTS["EvenMFail"] = _num(fe)

    # -- Refutation: g(x)=cx does NOT conjugate T_(a,b) to T_(ca,cb).
    n = 0
    lifts = 0
    for a in (3, 5, 7):
        for b in (1, 3, 5):
            for c in find_cycles(a, b, seed_max=800, max_steps=20000):
                for k in (3, 5, 7, 9):
                    n += 1
                    img = tuple(k * x for x in c.elements)
                    if all(mv.step(img[i], k * a, k * b) == img[(i + 1) % len(img)]
                           for i in range(len(img))):
                        lifts += 1
    rec("T-noconj", "cC is NEVER a cycle of T_(ca,cb) (the refuted conjugacy)",
        n, lifts == 0)
    FACTS["NoconjCases"] = _num(n)
    FACTS["NoconjHits"] = _num(lifts)

    # -- Thm: normal form is (a,1) iff rad(b) | a.
    n = 0
    ok = True
    for a in range(1, 120):
        for b in range(1, 120, 2):
            rad_divides = all(a % p == 0 for p in mv.factorise(b))
            n += 1
            ok &= ((normal_form(a, b) == (a, 1)) == rad_divides)
    rec("T-radical", "nf(a,b) = (a,1) iff rad(b) | a  (b odd)", n, ok)

    # -- q-ary: the two symmetries and the residue obstruction.
    import itertools
    import qary as QA

    def qcoeffs(q, lo, hi, cap):
        return list(itertools.product(range(lo, hi), repeat=q - 1))[:cap]

    n = 0
    ok = True
    for q in (2, 3, 4, 5):
        for aa in qcoeffs(q, 0, 4, 30 if not quick else 8):
            for bb in qcoeffs(q, 0, 4, 30 if not quick else 8):
                m = QA.QMap(q, aa, bb)
                m2 = m.scaled(q)
                for x in range(1, 40):
                    n += 1
                    if x % q == 0:
                        ok &= (m2.step(x) == m.step(x))
                    else:
                        ok &= (m2.step(x) == q * m.step(x))
                        ok &= (m2.step(m2.step(x)) == m.step(x))
    rec("T-qscale", "q-ary scaling: F_(qa,qb) refines F_(a,b)", n, ok)

    n = 0
    ok = True
    for q in (2, 3, 5, 7):
        for aa in qcoeffs(q, 1, 4, 25 if not quick else 6):
            for bb in qcoeffs(q, 0, 4, 25 if not quick else 6):
                m = QA.QMap(q, aa, bb)
                for d in range(1, 2 * q):
                    if math.gcd(d, q) != 1:
                        continue
                    md = m.offset_scaled(d)
                    for x in range(1, 40):
                        n += 1
                        ok &= (md.step(d * x) == d * m.step(x))
    rec("T-qtwist", "q-ary twisted scaling: n -> dn permutes the branches",
        n, ok)

    n = 0
    ngrow = 0
    ok = True
    QMAX = 5 if not quick else 3
    for q in range(2, QMAX + 1):
        for aa in qcoeffs(q, 0, 4, 25 if not quick else 6):
            for bb in qcoeffs(q, 0, 4, 25 if not quick else 6):
                m = QA.QMap(q, aa, bb)
                g = QA.residue_graph(m)
                for r in QA.escaping_residues(m):
                    vis = set()
                    j = r
                    while j not in vis:
                        vis.add(j)
                        j = g[j]
                    grows = all(m.a[k - 1] >= 2 or
                                (m.a[k - 1] == 1 and m.b[k - 1] >= 1)
                                for k in vis)
                    for x in range(r, 200, q):
                        if x < 1:
                            continue
                        t, ci = m.orbit(x, max_steps=60, value_cap=10 ** 60)
                        n += 1
                        # (i) never divides
                        ok &= not any(y % q == 0 for y in t[1:])
                        # (ii) and grows, when the growth condition holds
                        if grows:
                            ngrow += 1
                            ok &= (ci is None and (len(t) < 3 or t[-1] > t[0]))
    rec("T-resobs", "residue obstruction: escaping residues never divide, and "
        "diverge under the growth condition", n, ok)
    FACTS["ResobsQ"] = str(QMAX)
    FACTS["ResobsOrbits"] = _num(n)
    FACTS["ResobsGrowth"] = _num(ngrow)

    # -- q-ary attracting sublattice: the induced coefficients are PERMUTED.
    n = 0
    ok = True
    for q in (2, 3, 4, 5, 7):
        for mm in range(2, 8):
            if math.gcd(mm, q) != 1:
                continue
            for aa in qcoeffs(q, 1, 4, 12 if not quick else 4):
                for bb in qcoeffs(q, 0, 4, 12 if not quick else 4):
                    A = [mm * x for x in aa]
                    B = [mm * x for x in bb]
                    G = QA.QMap(q, A, B)
                    H = QA.QMap(q,
                                [A[(mm * j) % q - 1] for j in range(1, q)],
                                [B[(mm * j) % q - 1] // mm for j in range(1, q)])
                    for k in range(1, 40):
                        n += 1
                        ok &= (G.step(mm * k) % mm == 0)
                        ok &= (G.step(mm * k) // mm == H.step(k))
    rec("T-qattract", "attracting sublattice: the induced map has coefficients "
        "a'_j = a_(mj mod q), b'_j = b_(mj mod q)/m", n, ok)

    # -- the primality map of the "beyond modularity" section.  Memoised, so
    #    the range the paper quotes in prose is also the range checked here.
    LIM = 4000 if quick else 200000
    seen_cycles, _basins, failed, _peak = primality_census(LIM)
    ok = (failed == 0 and len(seen_cycles) == 2)
    rec("T-primmap", "primality map: every seed tested is eventually periodic, "
        "with exactly two cycles", LIM, ok)

    # -- carykh's (k, m) pairs for 3x+5, and the cycle-equation bound.
    km = {(c.k, c.m) for c in find_cycles(3, 5, seed_max=800 if not quick else 200,
                                          max_steps=20000)}
    n = len(km)
    ok = {(3, 5), (17, 27)} <= km and all(2 ** m > 3 ** k for k, m in km)
    rec("T-km", "3x+5 has cycles with (k,m) = (3,5) and (17,27), and every "
        "cycle has 2^m > a^k", n, ok)
    FACTS["KmOne"] = "3, 5"
    FACTS["KmTwo"] = "17, 27"

    # -- Prop: the b = 0 relative peak is exactly 2^(t-1+2^-t).
    n = 0
    ok = True
    PEAK_N = 200000 if not quick else 5000
    meas = []
    for t in (1, 2, 3):
        st = growth_statistics(2 ** t, 0, n_max=PEAK_N, max_steps=2000,
                               value_cap=10 ** 24)
        exact = 2.0 ** (t - 1 + 2.0 ** -t)
        n += 1
        ok &= (abs(st["peak"] - exact) < 5e-7)
        meas.append((exact, st["peak"]))
    rec("T-peak", "b = 0, a = 2^t: geometric mean relative peak is "
        "2^(t-1+2^-t)", n, ok)
    FACTS["PeakN"] = _num(PEAK_N)
    FACTS["PeakOne"] = "%.6f" % meas[0][0]
    FACTS["PeakTwo"] = "%.6f" % meas[1][0]
    FACTS["PeakThree"] = "%.6f" % meas[2][0]
    # "six decimal places" is not an observation typed in after the fact: the
    # tolerance above IS that claim, so the check fails if agreement is worse.
    FACTS["PeakDigits"] = "six"

    # -- Thm: negation duality.
    n = 0
    ok = True
    for a in range(1, 12):
        for b in range(1, 30):
            for s in range(1, 30):
                t1, _ = mv.orbit(s, a, -b, max_steps=60, value_cap=10 ** 18)
                t2, _ = mv.orbit(-s, a, b, max_steps=60, value_cap=10 ** 18)
                n += 1
                if [-x for x in t1] != t2:
                    ok = False
    rec("T-neg", "negation duality: -T_{a,b}(n) = T_{a,-b}(-n)", n, ok)

    total = len(R)
    passed = sum(1 for _, _, _, v in R if v == "PASS")
    lines = ["Numerical verification of the paper's theorems",
             "(these are checks, not proofs; the proofs are in the paper)",
             "=" * 78, ""]
    for tag, claim, cases, verdict in R:
        lines.append(f"{tag:<10} {verdict:<8} {cases:>9} cases   {claim}")
    lines.append("")
    lines.append(f"{passed}/{total} checks pass")
    write("verification.txt", "\n".join(lines) + "\n")

    # The plain-text claims above are written for the .txt report and contain
    # characters (^, _, *, {}) that are not valid LaTeX outside maths mode, so
    # the paper gets its own typeset wording, keyed by tag.
    TEX_CLAIM = {
        "T-halve":  r"$T_{2a,2b}$ refines $T_{a,b}$: one extra even term after "
                    r"each odd step",
        "T-scale":  r"$T_{a,db}(dn) = d\,T_{a,b}(n)$ for odd $d$",
        "T-attr":   r"$p \mid \gcd(a,b)$ forces every orbit into "
                    r"$p^{v_p(b)}\mathbb{Z}$",
        "T-rep":    r"$\min(v_p(n), v_p(b))$ is an orbit invariant when "
                    r"$p \mid b$, $p \nmid a$",
        "T-norm":   r"the normal form is coprime and idempotent for "
                    r"$a \geq 1$; $a = 0$ needs no reduction",
        "T-parity": r"$a+b$ odd with $a,b \geq 1$: no orbit is ever periodic",
        "T-desc":   r"$a=1$, $b$ odd: every orbit cycles, least cycle element "
                    r"$\leq b$",
        "T-const":  r"$a=0$: exactly one cycle, of period $v_2(b)+1$",
        "T-shape":  r"$b=0$: every orbit cycles iff $a$ is a power of two, "
                    r"period $\log_2 a + 1$",
        "T-cyceq":  r"cycle equation "
                    r"$n_1(2^m - a^k) = b\sum_i a^{k-i}2^{d_1+\cdots+d_{i-1}}$",
        "T-decomp": r"the $d$-graded part of $\mathrm{Cyc}(T_{a,b})$ is "
                    r"$d \cdot \mathrm{Cyc}^{\ast}(T_{a,b/d})$",
        "T-attred": r"the attracting reduction is a period-preserving "
                    r"bijection on cycles",
        "T-Zhalf":  r"$\Z_{>0}$ invariant iff $a+b \geq 1$; $\Z_{<0}$ "
                    r"invariant iff $b \leq a-1$",
        "T-Zcross": r"over $\Z$ the sign changes only at odd $n$ with "
                    r"$|n| \leq |b|/a$",
        "T-one":    r"$1$ is periodic iff its orbit meets a power of two",
        "T-onestep": r"$a+b = 2^k$ gives a cycle through $1$ of period $k+1$",
        "T-desc2b": r"every cycle of $x+b$ lies in $[1, 2b]$",
        "T-seedscale": r"$n$ on a cycle of $ax+b$ $\Rightarrow$ $mn$ on one "
                    r"of $ax+mb$, for \emph{odd} $m$",
        "T-noconj": r"$cC$ is never a cycle of $T_{ca,cb}$ -- the refuted "
                    r"conjugacy",
        "T-radical": r"$\mathrm{nf}(a,b) = (a,1)$ iff "
                    r"$\operatorname{rad}(b) \mid a$",
        "T-qscale": r"$q$-ary scaling: $F_{q\mathbf a, q\mathbf b}$ refines "
                    r"$F_{\mathbf a,\mathbf b}$",
        "T-qtwist": r"$q$-ary twisted scaling: $n \mapsto dn$ permutes the "
                    r"branches",
        "T-resobs": r"escaping residues never divide, and diverge under the "
                    r"growth condition",
        "T-primmap": r"primality map: every seed tested is eventually periodic, "
                    r"with exactly two cycles",
        "T-qattract": r"attracting sublattice: the induced coefficients are "
                    r"$a'_j = a_{mj \bmod q}$, $b'_j = b_{mj \bmod q}/m$ "
                    r"-- \emph{permuted}",
        "T-tier":   r"knowledge ladder: \textsc{open} $=$ minimal with an open "
                    r"normal form, \textsc{decided} $=$ the $a=1$ row, "
                    r"\textsc{closed} $=$ proved with closed-form cycles",
        "T-km":     r"$3x+5$ realises $(k,m) = (3,5)$ and $(17,27)$, and "
                    r"every cycle found satisfies $2^{m} > a^{k}$",
        "T-peak":   r"$b=0$, $a = 2^{t}$: the geometric mean of "
                    r"$\max(\mathrm{orbit}(n))/n$ is $2^{t-1+2^{-t}}$",
        "T-neg":    r"$T_{a,-b}(n) = -T_{a,b}(-n)$",
    }
    tex = [r"\texttt{%s} & %s & $%d$ & %s \\" %
           (tag.replace("_", r"\_"), TEX_CLAIM.get(tag, ""), cases,
            r"\ok" if v == "PASS" else r"\bad")
           for tag, claim, cases, v in R]
    write("verification.tex",
          "%% generated by generate_data.py -- do not edit\n" + "\n".join(tex) + "\n")
    return passed == total


# ======================================================================

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--quick", action="store_true",
                    help="smaller search windows (seconds instead of minutes)")
    args = ap.parse_args()
    q = args.quick

    print("[1/9] classification grid")
    table_grid(12, 12)

    print("[2/9] carykh's 6x6 grid, resolved")
    table_carykh()

    print("[3/9] cycle census, 3x+b row")
    A3_SEEDS = 400 if q else 20000
    A3_WIDE = 2000 if q else 100000
    A3_STEPS = 4000 if q else 200000
    a3 = table_row_cycles(3, 99, seed_max=A3_SEEDS, max_steps=A3_STEPS,
                          stem="row_a3")
    # the stability claim the paper makes about this window, actually tested
    print("    stability: recounting at the wider window ...")
    t0 = time.time()
    moved = sum(1 for b, n, _p, _nf in a3
                if len(find_cycles(3, b, seed_max=A3_WIDE,
                                   max_steps=A3_STEPS)) != n)
    print(f"    ({time.time() - t0:.1f}s, {moved} count(s) changed)")
    vals = sorted({n for _b, n, _p, _nf in a3})
    FACTS["RowThreeValues"] = (", ".join("$%d$" % v for v in vals[:-1])
                               + " and $%d$" % vals[-1])
    FACTS["RowThreeMissing"] = ", ".join(
        "$%d$" % v for v in range(1, max(vals)) if v not in vals) or "none"
    FACTS["RowSeeds"] = _num(A3_SEEDS)
    FACTS["RowWide"] = _num(A3_WIDE)
    FACTS["RowSteps"] = _num(A3_STEPS)
    FACTS["RowMoved"] = _num(moved)

    print("[4/9] cycle census, ax+1 column")
    table_row_cycles_ax1(q)

    print("[4b/9] cycle census, 1x+b row (the solved descent family)")
    table_row_cycles(1, 79, seed_max=400 if q else 20000,
                     max_steps=4000 if q else 200000, stem="row_a1")

    print("[5/9] divisor decomposition")
    table_decomposition(3, [5, 7, 25, 35, 49, 65], seed_max=400 if q else 20000,
                        max_steps=4000 if q else 200000)

    print("[6/9] density of open universes")
    table_density([10, 50, 100, 250, 500] if q
                  else [10, 50, 100, 250, 500, 1000, 2000])

    print("[6b/9] knowledge ladder")
    table_tiers([10, 50, 100, 250, 500] if q else [10, 50, 100, 250, 500, 1000])

    print("[7/9] growth statistics")
    table_growth(8, 8, n_max=500 if q else 5000)

    print("[8/9] the primality map")
    table_primcycles(4000 if q else 200000)
    table_primedensity(q)
    facts_qdrift()

    print("[9/9] inline figures quoted in the prose")
    facts_cycle_through_one(60 if q else 200, 20 if q else 60)
    facts_c4(3, 15 if q else 39, 15 if q else 39, 200 if q else 600)
    facts_window(3, 71, 600 if q else 3000, 3000 if q else 20000,
                 4000 if q else 200000)

    print("verification suite")
    ok = verify(q)

    write_facts()

    print("\ndone." if ok else "\ndone -- WITH FAILURES")
    return 0 if ok else 1


def table_row_cycles_ax1(q: bool) -> None:
    """Cycle counts down the b = 1 column, a odd."""
    rows = []
    for a in range(1, 40, 2):
        cs = find_cycles(a, 1, seed_max=400 if q else 20000,
                         max_steps=4000 if q else 200000)
        u = classify(a, 1)
        rows.append((a, len(cs), sorted(c.length for c in cs), u.odd_drift))
    lines = ["Cycle census for f(x) = a*x + 1,  a odd",
             "(b = 1 forces gcd(a,b) = 1, so every one of these is primitive "
             "and irreducible)",
             "=" * 78, "",
             f"{'a':>5} {'cycles':>7} {'drift a/4':>10}  cycle lengths"]
    for a, n, ls, d in rows:
        lines.append(f"{a:>5} {n:>7} {d:>10.2f}  {ls}")
    write("col_b1.txt", "\n".join(lines) + "\n")
    write("col_b1.tex",
          "%% generated by generate_data.py -- do not edit\n" +
          "\n".join(r"$%d$ & $%d$ & $%.2f$ & %s \\" %
                    (a, n, d, ", ".join(map(str, ls)) if ls else "---")
                    for a, n, ls, d in rows) + "\n")


if __name__ == "__main__":
    raise SystemExit(main())
